### ISSUE TITLE
train.py file missing

### ISSUE THREAD

**Issue by jayurbain** [chinokenochkan/vox2vox#2]
Well I didn't get too far, your train.py file is missing.

Thanks

**Comment by ahmedshingaly** [comment]
I also cannot find train.py, best guess is [vox2vox.py](https://github.com/chinokenochkan/vox2vox/blob/master/vox2vox/vox2vox/vox2vox.py) is actually train.py file renamed!

**Comment by enochkan** [comment]
My apologies for the late reply. @ahmedshingaly is correct. vox2vox.py is the train.py. I will rename it asap to avoid further confusion.

**Comment by ahmedshingaly** [comment]
thanks alot for the detailed [article](https://towardsdatascience.com/volumetric-medical-image-segmentation-with-vox2vox-f5350ed2094f) explaining your code and sharing this repository.
it would also be helpful if you could refer to a sample dataset to run the code. thanks in advance

**Comment by enochkan** [comment]
@jayurbain @ahmedshingaly thank you for raising this issue. I have renamed vox2vox.py as train.py. Closing this issue
